### ISSUE TITLE
Stability of Thumbnail Server

### ISSUE THREAD

**Issue by curran** [vizhub-studio/vizhub-legacy#140]
```
(node:8300) UnhandledPromiseRejectionWarning: TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
0|image-ge |     at /home/ubuntu/vizhub/packages/imageGenerationService/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21
0|image-ge |   -- ASYNC --
0|image-ge |     at Frame.<anonymous> (/home/ubuntu/vizhub/packages/imageGenerationService/node_modules/puppeteer/lib/helper.js:111:15)
0|image-ge |     at Page.setContent (/home/ubuntu/vizhub/packages/imageGenerationService/node_modules/puppeteer/lib/Page.js:665:42)
0|image-ge |     at Page.<anonymous> (/home/ubuntu/vizhub/packages/imageGenerationService/node_modules/puppeteer/lib/helper.js:112:23)
0|image-ge |     at /home/ubuntu/vizhub/packages/imageGenerationService/src/generateScreenshot.js:23:12
0|image-ge |     at new Promise (<anonymous>)
0|image-ge |     at generateScreenshot (/home/ubuntu/vizhub/packages/imageGenerationService/src/generateScreenshot.js:15:18)
0|image-ge |     at processTicksAndRejections (internal/process/task_queues.js:85:5)
0|image-ge |     at async Object.generateImages (/home/ubuntu/vizhub/packages/imageGenerationService/src/generateImages.js:11:28)
0|image-ge |     at async UpdateImages.execute (/home/ubuntu/vizhub/packages/useCases/src/interactors/updateImages.js:41:22)
0|image-ge |     at async Promise.all (index 0)
0|image-ge | (node:8300) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
0|image-ge | (node:8300) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by curran** [comment]
Idea: just kill the server every hour and let PM2 revive it.

The main instability is when errors happen that are not detected or caught by the try/catch.

**Comment by curran** [comment]
TODO check back with server to see if 1 hour restart interval took effect

ssh -i nv.pem ubuntu@54.174.10.146

**Comment by curran** [comment]
It seems to have worked.
